Repository monstertau/money-thrower, pull requests merged in 2021-11, with the labels that each got.

#35 Hot fix forgot pasword feature
  money-core/controller/change-password.go
  money-core/repository/redis.go
  money-core/service/change-password.go
  money-core/service/mail.go
  money-core/view/change-password.go
Labels: bug

#51 Hotfix/forgot password
  money-web/src/app/authentication/change-pass/change-pass.component.html
  money-web/src/app/authentication/change-pass/change-pass.component.ts
Labels: bug

#66 Feature/add transaction integration
  money-web/src/app/home/home.module.ts
  money-web/src/app/home/topbar/topbar-transaction/topbar-transaction.component.html
  money-web/src/app/home/topbar/topbar-transaction/topbar-transaction.component.ts
  money-web/src/app/home/topbar/topbar.component.css
  money-web/src/app/home/topbar/topbar.component.html
  money-web/src/app/services/category.service.spec.ts
  money-web/src/app/services/category.service.ts
  money-web/src/app/services/transaction.service.ts
  money-web/src/app/transaction-add/transaction-add-category/transaction-add-category.component.css
  money-web/src/app/transaction-add/transaction-add-category/transaction-add-category.component.html
  money-web/src/app/transaction-add/transaction-add-category/transaction-add-category.component.ts
  money-web/src/app/transaction-add/transaction-add-wallet/transaction-add-wallet.component.html
  money-web/src/app/transaction-add/transaction-add-wallet/transaction-add-wallet.component.ts
  money-web/src/app/transaction-add/transaction-add.component.html
  money-web/src/app/transaction-add/transaction-add.component.ts
  money-web/src/app/transaction-add/transaction-add.module.ts
  money-web/src/app/transaction/transaction-detail/transaction-detail.component.ts
  money-web/src/app/transaction/transaction-list/transaction-list.component.html
  money-web/src/app/transaction/transaction-list/transaction-list.component.ts
  money-web/src/app/transaction/transaction.component.ts
  money-web/src/app/view-model/category.ts
  money-web/src/app/view-model/transactions.ts
Labels: front-end, integration

#69 Feature/category
  money-web/src/app/app-routing.module.ts
  money-web/src/app/category/category-detail/category-detail.component.css
  money-web/src/app/category/category-detail/category-detail.component.html
  money-web/src/app/category/category-detail/category-detail.component.ts
  money-web/src/app/category/category.component.css
  money-web/src/app/category/category.component.html
  money-web/src/app/category/category.component.ts
  money-web/src/app/category/category.module.ts
  money-web/src/app/components/loading-spinner2/loading-spinner2.component.css
  money-web/src/app/components/loading-spinner2/loading-spinner2.component.html
  money-web/src/app/components/loading-spinner2/loading-spinner2.component.ts
  money-web/src/app/home/home.module.ts
  money-web/src/app/home/sidebar/sidebar.component.html
  money-web/src/app/home/topbar/topbar-category/topbar-category.component.css
  money-web/src/app/home/topbar/topbar-category/topbar-category.component.html
  money-web/src/app/home/topbar/topbar-category/topbar-category.component.ts
  money-web/src/app/home/topbar/topbar.component.html
  money-web/src/app/services/category.service.ts
  money-web/src/app/services/common.service.ts
Labels: front-end

#85 Category Improvements
  money-web/src/app/category/category-detail/category-detail.component.html
Labels: front-end
